# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\\
        src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "basketapi:dev"
    ports:
    - "127.0.0.1:57015:57100"
    - "127.0.0.1:57215:57300"
    volumes:
    - "C:\\Users\\andre\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\src\\\
      Services\\Basket\\Basket.API:/app:rw"
    - "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\src:/src:rw"
    - "C:\\Users\\andre\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\andre\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\andre\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_4_16_18_27_07:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\\
        src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57016:57100"
    - "127.0.0.1:57216:57300"
    volumes:
    - "C:\\Users\\andre\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\src\\\
      Services\\Catalog\\Catalog.API:/app:rw"
    - "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\src:/src:rw"
    - "C:\\Users\\andre\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\andre\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\andre\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_4_16_18_27_07:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\\
        src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "discountgrpc:dev"
    ports:
    - "127.0.0.1:57017:57100"
    - "127.0.0.1:57217:57300"
    volumes:
    - "C:\\Users\\andre\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\src\\\
      Services\\Discount\\Discount.Grpc:/app:rw"
    - "C:\\Users\\andre\\OneDrive\\Ciro Dev 2024\\DotNet8\\eshop-microservices\\src:/src:rw"
    - "C:\\Users\\andre\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\andre\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\andre\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_4_16_18_27_07:/var/opt/rider-debugger:rw"
    working_dir: "/app"
